name: Build and Deploy

on: [ push, pull_request ]
      
jobs:
  build_apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/retro_cam
    steps:
    - uses: actions/checkout@master
    - uses: subosito/flutter-action@v1.5.0
    - run: flutter pub get
    - run: flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: ios-build
        path: build/ios/iphoneos

  build_ios:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - uses: subosito/flutter-action@v1.5.0
    - run: flutter pub get
    - run: flutter build ios --no-codesign
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/apk/release
    
  deploy_apk:
    runs-on: ubuntu-latest
    needs: build_apk
    steps:
      - uses: actions/checkout@master
      - name: Download Apk
        uses: actions/download-artifact@master
        with:
          name: apk-build
      - name: Upload Apk
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
