name: Build and Deploy

on: [ push, pull_request ]
      
jobs:
  build_apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/retro_cam
    steps:
    - uses: actions/checkout@master
    - uses: subosito/flutter-action@v1.5.0
    - run: flutter pub get
    - run: flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: client/retro_cam/build/app/outputs/apk/release

  build_ios:
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./client/retro_cam
    steps:
    - uses: actions/checkout@master
    - uses: subosito/flutter-action@v1.5.0
    - run: flutter pub get
    - run: flutter build ios --no-codesign
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: ios-build
        path: client/retro_cam/build/ios/iphoneos
    
  deploy_apk:
    runs-on: ubuntu-latest
    needs: build_apk
    defaults:
      run:
        working-directory: ./client/retro_cam
    steps:
      - uses: actions/checkout@master
      - name: Download Apk
        uses: actions/download-artifact@master
        with:
          name: apk-build
      - name: Upload Apk
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: >-
            ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PC_API_6633098807224626672_395
            }}
          channelId: live
          projectId: pc-api-6633098807224626672-395
